### PR TITLE
Make finding official

### LINKED ISSUE #1: Ship the Evergreen Web Finding

### PR DESCRIPTION
**Pull request by dbaron**
Fixes #1.

### CODE REVIEW

**Review by travisleithead — APPROVED** [review]

**Review by torgo — APPROVED** [review]
I 🌲 it.

**Review by slightlyoff — APPROVED** [review]
LGTM++

**Review by hadleybeeman — APPROVED** [review]
👍

**Review by timbl — APPROVED** [review]

**Review by ylafon — APPROVED** [review]

**Review by plinss — APPROVED** [review]

**Review by triblondon — APPROVED** [review]
`drag` => `hold`, otherwise great. 👍

**Pull request merged**
